renamed init.d scripts to bring them into line with the naming used by ivftp

diff --git a/ivsftp/etc/init.d/ivsftp b/ivsftp/etc/init.d/ivsftp
--- a/ivsftp/etc/init.d/ivsftp
+++ b/ivsftp/etc/init.d/ivsftp
@@ -7,11 +7,11 @@
 . /iv/env/bin/activate
 . /iv/impactvizor-pipeline/conf/sftp_prod.sh
 
-name=$(basename "$0");
-user="ivftp"
-pid_file="/var/run/$name.pid"
+user="ivftp" # share user name with ivftp
 dir="/iv/impactvizor-pipeline/ivsftp"
-cmd=("python" "sftp.py" "-nofork")
+pid_file="/var/run/ivsftp.pid"
+log="/var/log/ivsftp"
+cmd=("python" "sftp.py" "-nofork" "-log-dir" "${log}")
 
 if [ "${IVSFTP_ADDR}" != "" ]; then
 	cmd+=("-addr" "${IVSFTP_ADDR}")
@@ -37,23 +37,43 @@ is_running() {
     [ -f "$pid_file" ] && ps "$(get_pid)" >/dev/null 2>&1
 }
 
+wait_for_socket() {
+	host="${IVSFTP_ADDR}";
+	port="${IVSFTP_PORT}";
+	attempts="4";
+	sleep_sec="1";
+
+	nattempts=0;
+	status=1;
+	while [ "${nattempts}" -lt "${attempts}" ]; do
+		nattempts+=$((nattempts+1))
+		if nc -z "${host}" "${port}" 2>&1; then
+			status=0;
+			break;
+		fi
+		sleep "${sleep_sec}";
+	done
+	return ${status}
+}
+
 case "$1" in
     start)
     if is_running; then
         echo "Already started"
     else
-        echo "Starting $name"
+        echo "Starting ivsftp"
         cd "$dir" || exit 1;
-        runuser -u "${user}" -- "${cmd[@]}" >"/iv/log/${name}/${name}.out" 2>&1 & echo $! > "$pid_file";
-        if ! is_running; then
-            echo "Unable to start, check /iv/log/${name}/${name}.out and /iv/log/${name}/${name}.log for errors"
+        runuser -u "${user}" -- "${cmd[@]}" >"${log}/sftp.out" 2>&1 & echo $! > "$pid_file";
+        disown "$(get_pid)"
+        if ! wait_for_socket; then
+            echo "Unable to start, check ${log}/sftp}.out and ${log}/sftp.log for errors"
             exit 1
         fi
     fi
     ;;
     stop)
     if is_running; then
-        echo -n "Stopping $name.."
+        echo -n "Stopping ivsftp.."
         kill "$(get_pid)";
         for i in {1..10}
         do
